<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="CustomerJourney" nsURI="http://CustomerJourney" nsPrefix="CustomerJourney">
  <eClassifiers xmi:type="ecore:EClass" name="Persona">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Actor" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Actor"/>
    <eStructuralFeatures xmi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xmi:type="ecore:EAttribute" name="age" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xmi:type="ecore:EAttribute" name="position" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Stage">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_UseCase" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//UseCase"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Step">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_UseCase" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//UseCase"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="expects">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Abstraction" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Abstraction"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Dependency" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Touchpoint">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="ProblemSpace">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Actor" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Actor"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="supports">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Dependency" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="SolutionSpace">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_UseCase" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//UseCase"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Issue">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_UseCase" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//UseCase"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Expectation">
    <eStructuralFeatures xmi:type="ecore:EReference" name="base_Actor" ordered="false"
        eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Actor"/>
  </eClassifiers>
</ecore:EPackage>
